### PR TITLE
Add hint examples

### PR DESCRIPTION
**Pull request by phill-85**
Examples copied from the paternfly site. Hope this is ok?

### CODE REVIEW

**Comment by phill-85** [comment]
> I would just ask you to keep the `Cargo.lock` file. As this is an application, cloning it should default to using the same versions as committed and tested.
> 
> Unless there's another good reason not to do this.

I was using a local copy of paternfly-yew as the hint changes are not part of the revision patched in Cargo.toml, so the lock file changed and was adding noise to a diff.

I guess as Carog.toml patches paternfly-yew to a specific revision the code will fail as the hint component is not in that revision. How do you deal with this?

**Comment by ctron** [comment]
Normally you replace the rev field with the new commit SHA, once it is pushed to the main branch.

**Comment by phill-85** [comment]
This should be good to go!

**Comment by ctron** [comment]
Merged, thanks for the PR!

**Pull request merged**
